# Generated by Django 6.0.6 on 2026-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_spot_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('CAMIONETA', 'Camioneta'), ('OTRO', 'otro')], default='AUTO', max_length=10),
        ),
    ]
