# Generated by Django 6.0.6 on 2026-06-28 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_vehiculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='entrada',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Entrada'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Cobrado')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=20, verbose_name='Metodo de Pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.spot', verbose_name='Cochera')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.vehiculo', verbose_name='Vehiculo')),
            ],
        ),
    ]
