# Generated by Django 6.0.6 on 2026-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_spot_entrada_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Entrada'),
        ),
    ]
