# Generated by Django 6.0.6 on 2026-06-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_spot_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='estado',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado')], default='LIBRE', max_length=10, verbose_name='Estado Cochera'),
        ),
    ]
