# Generated by Django 6.0.6 on 2026-06-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_spot_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='entrada',
        ),
    ]
