# Generated by Django 6.0.6 on 2026-06-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_spot_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='ingreso',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Entrada'),
        ),
    ]
